alg_name: "LoRA"
model_name: "gpt2_xl"
device: 0

lora_type: "adalora"
layers: []
num_steps: 20
batch_size: 1
max_length: 30
lr: 5e-03
weight_decay: 0
kl_factor: 0
rank: 8
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["c_fc", "c_proj"]
model_parallel: false